name: check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install development tools
        run: brew install just shellcheck shfmt uv
      - name: Check
        run: just check
